### ISSUE TITLE
Consider whether VerifiableTimestamp and TimestampCommitment are both needed

### ISSUE THREAD

**Issue by sgreenbury** [alan-turing-institute/trustchain#102]
Qs:
 - `VerifiableTimestamp` looks very similar to `TimestampCommitment`; are both needed?
 - the `verify_content` method in `VerifiableTimestamp` verifies the expected data in the DID commitment; is this the cleanest way to do it? (at least this is *validating* the content, not verifying it)
 - why not have `VerifiableTimestamp` as a trait (without the `verify_content` method), which is implemented by `TimestampCommitment`?
 - most importantly, how do we make sure that the `validate_pow_hash` is called as part of the content verification procedure?

First step will be to draw a diagram of the commitments & related traits.

**Comment by thobson88** [comment]
### UML diagram

![DID-Verification drawio (2)](https://github.com/alan-turing-institute/trustchain/assets/26117394/04c2b8b0-12b4-4734-a67c-69eab2a02a4f)

**Comment by thobson88** [comment]
Done in PR #105.

**Comment by thobson88** [comment]
### Updated UML diagram

![refactored-DID-Verification drawio](https://github.com/alan-turing-institute/trustchain/assets/26117394/b6d07648-b9f1-45dc-b7f1-0caa7f2e8842)

**Comment by sgreenbury** [comment]
Closed with #108
