### ISSUE TITLE
Generate create operation deterministically from mnemonic

### ISSUE THREAD

**Issue by sgreenbury** [alan-turing-institute/trustchain#117]
Construct a new ION DID from a mnemonic allowing transfer between mobile and desktop to facilitate [verifiable presentations](https://github.com/alan-turing-institute/trustworthy-id/issues/580).

**Comment by sgreenbury** [comment]
Next steps:
- Merge `117-mnemonic-create` (TODO: open PR)
- Merge https://github.com/alan-turing-institute/trustchain/pull/122

**Comment by thobson88** [comment]
Related to https://github.com/alan-turing-institute/trustchain-mobile/issues/23.
