### ISSUE TITLE
DID timestamp verification

### ISSUE THREAD

**Issue by thobson88** [alan-turing-institute/trustchain#24]
DID timestamps need to be determined by:
 - finding the DID operation in the ION MongoDB
 - looking up the corresponding transaction on the Bitcoin blockchain
 - extracting the OP RETURN data to get the IPFS address
 - querying IPFS to get the document “delta” and “recovery commitment” (suffix data)
 - reconstructing the DID suffix from the suffix data
 - hashing the DID suffix at comparing that hash to the given DID

If the hashes match, we have obtained a pre-image for the hash using data retrieved from IPFS at an address written into a bitcoin transaction's OP RETURN data. This proves that the data are unchanged since the transaction was published in the blockchain, and therefore the timestamp of the transaction is also a timestamp for the data.

This timestamp *could* be inserted in the [DID Document Metadata](https://www.w3.org/TR/did-core/#did-document-metadata) in the Trustchain resolution step (using the `created` and `updated` fields), but that would make it part of the resolution, as opposed to verification, process. Conceptually, however, it is a verification step (particularly on the root DID) so the code belongs in the verifier module. We could make it optional for inclusion in the DID Document Metadata.

**Comment by sgreenbury** [comment]
Closed by #65
