### ISSUE TITLE
Visualisation of trustchain trees

### ISSUE THREAD

**Issue by thobson88** [alan-turing-institute/trustchain#29]
The aim is to be able to visualise chains of dDIDs.

One way would be to generate [graphviz](https://graphviz.org/) DOT language from a given chain of DIDs (maybe using the [graphviz-rust library](https://crates.io/crates/graphviz-rust)).

The DOT output could then be rendered as a static image or in a browser (with these [Node/JS libraries](https://github.com/CodeFreezr/awesome-graphviz#libs-for-node--js--jquery--d3)).

Here's a quick sketch of [what the result might look like](http://magjac.com/graphviz-visual-editor/?dot=digraph%20G%20%7B%0A%20%20%20%20rankdir%3DLR%3B%0A%20%20%20%20compound%3Dtrue%3B%0A%20%20%20%20subgraph%20cluster1%20%7B%0A%20%20%20%20%20%20%20%20fontsize%20%3D%2020%3B%0A%20%20%20%20%20%20%20%20fontname%20%3D%20%22Helvetica%22%3B%0A%20%20%20%20%20%20%20%20label%20%3D%20%22Root%20DID%20%5Cn%20EiA8yZ%22%3B%0A%20%20%20%20%20%20%20%20%23RootA%20-%3E%20B%3B%0A%20%20%20%20%20%20%20%20P1%20%5Bshape%3Dpoint%20style%3Dinvis%5D%0A%20%20%20%20%20%20%20%20subgraph%20timestamp1%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%2228%2F09%2F2022%5CnBlock%3A%20756094%22%5Bshape%3D%22none%22%20fontsize%3D18%20fontname%3D%22Helvetica%22%5D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20subgraph%20cluster2_1%20%7B%0A%20%20%20%20%20%20%20%20fontsize%20%3D%2020%3B%0A%20%20%20%20%20%20%20%20fontname%20%3D%20%22Helvetica%22%3B%0A%20%20%20%20%20%20%20%20label%20%3D%20%22dDID%20%5Cn%20EiB7xW%22%3B%0A%20%20%20%20%20%20%20%20%23RootA%20-%3E%20B%3B%0A%20%20%20%20%20%20%20%20P2_1%20%5Bshape%3Dpoint%20style%3Dinvis%5D%0A%20%20%20%20%20%20%20%20subgraph%20timestamp2_1%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%2229%2F09%2F2022%5CnBlock%3A%20756209%22%5Bshape%3D%22none%22%20fontsize%3D18%20fontname%3D%22Helvetica%22%5D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20subgraph%20cluster2_2%20%7B%0A%20%20%20%20%20%20%20%20fontsize%20%3D%2020%3B%0A%20%20%20%20%20%20%20%20fontname%20%3D%20%22Helvetica%22%3B%0A%20%20%20%20%20%20%20%20label%20%3D%20%22dDID%20%5Cn%20EiB4aX%22%3B%0A%20%20%20%20%20%20%20%20%23RootA%20-%3E%20B%3B%0A%20%20%20%20%20%20%20%20P2_2%20%5Bshape%3Dpoint%20style%3Dinvis%5D%0A%20%20%20%20%20%20%20%20subgraph%20timestamp2_2%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%2229%2F09%2F2022%5CnBlock%3A%20756211%22%5Bshape%3D%22none%22%20fontsize%3D18%20fontname%3D%22Helvetica%22%5D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20subgraph%20cluster3_1%20%7B%0A%20%20%20%20%20%20%20%20fontsize%20%3D%2020%3B%0A%20%20%20%20%20%20%20%20fontname%20%3D%20%22Helvetica%22%3B%0A%20%20%20%20%20%20%20%20label%20%3D%20%22dDID%20%5Cn%20EiB2jP%22%3B%0A%20%20%20%20%20%20%20%20%23RootA%20-%3E%20B%3B%0A%20%20%20%20%20%20%20%20P3_1%20%5Bshape%3Dpoint%20style%3Dinvis%5D%0A%20%20%20%20%20%20%20%20subgraph%20timestamp3_1%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%2230%2F09%2F2022%5CnBlock%3A%20756255%22%5Bshape%3D%22none%22%20fontsize%3D18%20fontname%3D%22Helvetica%22%5D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20%23%20Edges%0A%20%20%20%20P1%20-%3E%20P2_1%20%5Bltail%3Dcluster1%2Clhead%3Dcluster2_1%20minlen%3D3%5D%3B%0A%20%20%20%20P1%20-%3E%20P2_2%20%5Bltail%3Dcluster1%2Clhead%3Dcluster2_2%20minlen%3D3%5D%3B%0A%20%20%20%20P2_1%20-%3E%20P3_1%20%5Bltail%3Dcluster2_1%2Clhead%3Dcluster3_1%20minlen%3D3%5D%3B%0A%7D).

**Comment by sgreenbury** [comment]
Initial [implementation](https://github.com/alan-turing-institute/trustchain/blob/c58b38810c688ce6477cd1f20a093b1816f70aa0/trustchain-core/src/graph.rs) now merged in #52.
