### ISSUE TITLE
Include linting with clippy in pre-commit and actions workflows

### ISSUE THREAD

**Issue by sgreenbury** [alan-turing-institute/trustchain#38]
Add [clippy](https://github.com/rust-lang/rust-clippy):
- [x] Run `cargo clippy` and modify code accordingly
- [x] pre-commit [hooks](https://github.com/doublify/pre-commit-rust/blob/master/.pre-commit-hooks.yaml)
- [x] github [actions](https://github.com/actions-rs/clippy-check) workflows

**Comment by sgreenbury** [comment]
Another one to update here are the versions for Rust edition is 2021.

**Comment by edchapman88** [comment]
> Another one to update here are the versions for Rust edition is 2021.

This is complete.

**Comment by sgreenbury** [comment]
Also [dependabot](https://github.com/alan-turing-institute/trustchain/security/dependabot).

**Comment by sgreenbury** [comment]
Following recent merges to `main` it would make sense to revisit this and complete #39 after the above changes.
