### ISSUE TITLE
Implement issuing a verifiable presentation

### ISSUE THREAD

**Issue by sgreenbury** [alan-turing-institute/trustchain#59]
Include functionality for transforming from a VC to a VP. This process relates to the [W3C VC API](https://w3c-ccg.github.io/vc-api/#prove-presentation). See work in [didkit](https://github.com/spruceid/didkit/tree/main/cli#didkit-vc-issue-presentation) for reference.

**Comment by sgreenbury** [comment]
- [ ] Explore [`Presentation`](https://docs.rs/ssi/0.4.0/ssi/vc/struct.Presentation.html) and [didkit implementation](https://github.com/spruceid/didkit/tree/main/cli#didkit-vc-issue-presentation)
- [ ] Consider requirements with respect to FFI (#62, #63 )

**Comment by edchapman88** [comment]
Updates:
* Changes to `Issuer.sign()` and `Holder.sign_presentation()` to include `Option<LinkedDataProofOptions>` in the api.
   - For `Issuer.sign()`: if `None`, the default is used (which sets `ProofPurpose::AssertionMethod`).
   - For `Holder.sign_presentation()`: if `None`, `ProofPurpose::Authentication` is set along with the other fields from `Default::default()`.
* Change to `sign_presentation()` to ensure the `holder` field is set on presentations before they are signed.
* `Presentation.generate_proof()` attempts to resolve a DID provided in the `holder` field of the presentation.
   - This has implications for supporting the partial verification of presentations in the cases where the holder DID is either non-resolvable or non-verifiable.
   - It is not currently possible to sign presentations with non-resolvable DIDs
